### ISSUE TITLE
I'm creating an issue. Will it be worth a tip?

### ISSUE THREAD

**Issue by TechNickAI** [changecoin/testcommentrepo#180]

**Comment by testchangetip3** [comment]
Yeah, this is tip-worthy. Thanks a bunch. $1 @changetip

**Comment by changetip** [comment]
@gorillamania, the ChangeTip bot has delivered a tip for 0.00130 bitcoin to your account from @testchangetip3.

[What's this?](https://www.changetip.com/get-tips-online/github)
